AWSTemplateFormatVersion: 2010-09-09
Parameters:
  applicationStackS3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the application.template.yml template file
    Default: caw9-1570735779129
  cloudappwatchDBPassword:
    Type: String
    Description: Aurora master database password for cloudappwatch
    NoEcho: true

  shouldDeployService:
    Type: String
    Description: Should the ECS service be initialised
    AllowedValues:
      - true
      - false
    Default: false
Resources:
  cloudappwatch:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        parentStackName: !Ref AWS::StackName
        repositoryName: caw9/cloudappwatch
        shouldDeployService: !Ref shouldDeployService
        databasePassword: !Ref cloudappwatchDBPassword
      TemplateURL: !Join ['', ['https://s3.amazonaws.com/', !Ref applicationStackS3Bucket, '/cloudappwatch.template.yml']]

Outputs:
  LoadBalancerOutputcloudappwatch:
    Description: The external DNS address of the load-balancers
    Value: !GetAtt cloudappwatch.Outputs.LoadBalancerOutput
