apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  secret: TURJMU1ERTFPR0l6T0RoaVptRTRPRGxtWmpBME9HSTBZekk1WlRCbE9UY3lZbU5tWkdGbU5UZzVNMkV3Tm1VME16ZG1NakU0T1dGbE4yVTRNRGN3TldOaE5UTXdNekF6WXpFeVpqSXdaVGN3TURsbFkyRTRNalk0TkRVd1lUTmtaR1kyTmpFeFl6ZGhaRGt6WlRJME9HVXpNVGc0WW1Zd05tRmhOV1UxTlRnPQ==
